package org.jminiorm.query.generic;

import org.jminiorm.exception.DBException;

import java.util.List;
import java.util.Map;

/**
 * Represents a generic insert query, that is, one that insert rows in an arbitrary table.
 */
public interface IGenericInsertQuery extends IGenericQuery {

    /**
     * Sets the schema.
     *
     * @param schema
     * @return
     */
    IGenericInsertQuery schema(String schema);

    /**
     * Sets the table.
     *
     * @param table
     * @return
     */
    IGenericInsertQuery table(String table);

    /**
     * Specifies that the given column is generated by the database (i.e. auto increment).
     *
     * @param column
     */
    IGenericInsertQuery generatedColumn(String column);

    /**
     * Add one values(...) clause.
     *
     * @param values
     * @return
     */
    IGenericInsertQuery addOne(Map<String, Object> values);

    /**
     * Add many values(...) clauses (all the maps must have the same set of keys).
     *
     * @param values
     * @return
     */
    IGenericInsertQuery addMany(List<Map<String, Object>> values);

    /**
     * Executes the (batch) statement. If a generated column was set, then a key-value pair is added to all the maps
     * with the generated column and its generated value.
     */
    void execute() throws DBException;

}
